# INFO 201 Final Project -- Final Deliverable
# Section BH
# Group member: Sera Lee, Lele Zhang, Ivette Ivanov, Sohyun Han

library(ggplot2)
library(plotly)
library(dplyr)
library(bslib)
library(shiny)

# Color theme
my_theme <- bs_theme(version = 3, 
                     bootswatch = "flatly",
                     bg = "#F2E7D4", #background
                     fg = "black", #foreground color
                     )



## OVERVIEW TAB INFO

overview_tab <- tabPanel("Introduction",
   h1("The Relationship Between Occupation and Physical Health"),
   tags$b("BH-5 Group Members:"), p("Sohyun Han, Sera Lee, Ivette Immanov, Lele Zhang"),
   h3("Introduction"),
   
   img(src = 'https://cdn.pixabay.com/photo/2017/03/04/13/12/alarm-clock-2116007_1280.jpg', height="28%", width="28%", align="right"),
   
   p("In today’s society, where work plays a central role in our daily lives, 
   understanding the impact of specific occupation on individuals’ physical health 
   is a crucial topic. The background of one’s job can severely influence well-being, 
   including the risk factors to necessary lifestyle adjustments."),
   
   p("Past studies on work and health have focused on physical safety and mitigating occupational hazards. 
   Although these concerns still remain, this investigation aims to expand the discussion 
   to include deeper factors such as, mental health, stress, and sleep health."),
   
   p("By examining and comparing the data collected, we not only enhance our understanding 
   of individual health outcomes but also inform a broader societal discussion on work-life 
   balance, workplace wellness, and public health policies. Our discussion will dive into 
   the compelling questions aimed to investigate the correlation between one’s occupation 
   and physical health and to recognize the quantified pattern that emerges from this exploration."),
   
   
   tags$ol(
   tags$li(tags$b("How do physical activity levels vary among different occupations?")),
   p(""),
   tags$li(tags$b("What occupations among the dataset have the best/worst (average) quality of sleep?")),
   p(""),
   tags$li(tags$b("Does a higher salary in high-stress jobs equate to poorer physical health?")),
   p(""),),
   
   h3("Datasets Used"),
   p("The data set has been compiled from two sources: the U.S. Bureau of Labor Statistics Occupational Employment 
      and Wage Statistics (OEWS) program and Laksika Tharmalingam’s Sleep and Health dataset on Kaggle.
      The OEWS program surveys employers in all industries across all states including the District of Columbia. 
      The data is estimated based on responses collected over a 3-year period: May 2022, November 2021, May 2021, 
      November 2020, May 2020, and November 2019."),
   
   p(""),
   
   tags$ul(
   tags$b(tags$li(em("May 2022 National Occupational Employment and Wage Estimates."))),
   a("https://www.bls.gov/oes/current/oes_nat.htm"),
   p(""),
   p("The May 2022 National Occupational Employment and Wage Estimates was collected and generated 
     by he U.S. Bureau of Labor Statistics Occupational Employment and Wage Statistics (OEWS) program, 
     collected over a 3-year period and was last modified on April 25, 2023."),

   tags$li(tags$b(em("Sleep Health and Lifestyle Dataset."))),
   p(""),
   
   a("https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset"),
   p("The Sleep, Health, and Lifestyle dataset was collected and generated by Laksika Tharmalingam in 2023, 
      it was last modified on April 25, 2023, and no other external source is specified."),

   tags$li(tags$b("The comprehensive data set is available here on Github:")),
   a("https://github.com/imivanov-2034391/Info_201_Final_Project/blob/main/Comprehensive%20Physical%20Health%20and%20Occupational%20Statistics%20Dataset.csv"),
   
   ),
   p(""),
   h3("Limitations & Challenges"),
   
   img(src = 'https://haverfordlibrary.org/wp-content/uploads/2016/09/Bureau_of_labor_statistics_logo-1024x897.png', height="15%", width="15%", align="right"),
   
   p("The following visualizations are very much a limited snapshot of the sleep health of individuals 
      in a particular set of occupations within the past 3 years in the United States (as written in 2024)."),
   
   tags$b("Many types of occupations are not included, and thus this cannot be taken as truly representative 
      of the diverse workforce of the U.S. There is a small number of data points even within the existing 
      occupations in the dataset, and is a rather small sample of the variety of working individuals and their 
      sleeping patterns given the size of the U.S. population."),
   
   p(""),
    
   p("Additionally, the Sleep Health and Lifestyle dataset was acquired from Kaggle for student 
      research purposes and may therefore be biased."),
      
   p("As for the salary and wage statistics from the National Occupational 
      Employment and Wage Estimates dataset, there are two main challenges to be noted here. 
      Primarily, the timeframe in which the data was collected took place 
      over the COVID-19 pandemic and may have negatively influenced the wage statistics."),
      
      
  p("There is also the additional matter of how these statistics are not representative of change over a long period of time. 
      It is possible that the relationship between sleep health and occupation could have more variation and complexities to 
      consider over an entire decade for example, as opposed to a few years, especially as this is only a glimpse into the 
      momentary health of a few individuals."),
    
  tags$b("Overall, our compiled dataset is rather limited in terms of timeframe, the types of occupations represented, and simply the number of data points available."),

  h3("Related Works"),
  
  p(""),
  
  tags$ul(
    
    tags$li(tags$b(em("CDC (2022) Sleep for good health, Centers for Disease Control and Prevention."))),
    a("https://www.cdc.gov/sleep/features/getting-enough-sleep.html"),
    p(""),
    
    p("Contains background information on sleep health and quality, along with other sources on sleep quality, 
      disorders, and outreach programs. We used the CDC website in order to gain a basic understanding of how sleep may impact health."),
    
    tags$li(tags$b(em("‘Why sleep matters—the economic costs of insufficient sleep’, Rand Health Quarterly, 6(4), p. 11."))),
    a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5627640/"),
    p(""),
    
    p("Frames the issue of insufficient sleep as a matter of public health, and details everything related to that, 
        including economic factors, has the main objective of quantifying the cost of insufficient sleep. "),
    
    tags$li(tags$b(em("Lack of sleep costs Americans billions of dollars each year - CBS News"))),
    a("https://www.cbsnews.com/news/lack-of-sleep-costs-americans-billions-of-dollars-each-year/"),
    p("An article that we used to look at larger costs of sleep, was quoted in our story pitch. Contains figures from a few different studies."),
    
    tags$li(tags$b(em("Who gets the best sleep? Ethnic and socioeconomic 
                        factors related to sleep complaints, Journal of Sleep Medicine, 11(5), pp. 470–478. "))),
    a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2861987/ "),
    p("Indicates that there are a variety of socioeconomic factors that may lead to insufficient sleep, including wages."),
    
    p("A source that looks largely at the broader economic impact of sleep deprivation on the healthcare system. 
        While that isn’t the main focus of our project, it is one of the references that made us consider how economics 
        and finances play a role in regard to physical health such as sleep deprivation."),
    
    tags$li(tags$b(em("The association between sleep disorders, employment, and income among adults in the United States"))),
    a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9340609/"),
    p("It shows that people with poor sleep health have lower unemployment rates, 
      lower wages, and higher utilization of welfare income. 
      Considers a number of demographic factors such as age, race, and medical conditions."),
      
    p("A source that looks largely at the broader economic impact of sleep deprivation on the healthcare system. 
        While that isn’t the main focus of our project, it is one of the references that made us consider how economics 
        and finances play a role in regard to physical health such as sleep deprivation."),
  
  )) 



## VIZ 1 TAB INFO

viz_1_sidebar <- sidebarPanel(
  h3("Options"),
  checkboxInput (
    inputId = "phy_occ_plot_60" ,
    label = "Physical activity levels above 60"
  )
  
)

viz_1_main_panel <- mainPanel(
  h2("1. Physical activity levels among different occupations"),
  h3("Physical Activity vs. Occupation"),
  plotlyOutput(outputId = "phy_occ_plot")
)

viz_1_tab <- tabPanel("Physical Activity among Occupations",
  sidebarLayout(
    viz_1_sidebar,
    viz_1_main_panel
  )
)



## VIZ 2 TAB INFO

viz_2_sidebar <- sidebarPanel(
  h3("Select Sleep Quality"),
  radioButtons(
    inputId = "sle_occ_plot_type",
    label = "Select plot type:",
    choices = c("Best Quality of Sleep", "Worst Quality of Sleep"),
    selected = "Best Quality of Sleep"
  )
)

viz_2_main_panel <- mainPanel(
  h2("2. Best/worst (average) quality of sleep among different occupations"),
  h3("Sleep Median vs. Occupation"),
  plotlyOutput(outputId = "sle_occ_plot")
)

viz_2_tab <- tabPanel("Sleep Quality among Occupation",
                      sidebarLayout(
                        viz_2_sidebar,
                        viz_2_main_panel
                      )
)


## VIZ 3 TAB INFO

viz_3_sidebar <- sidebarPanel(
  h3("Choose a Health Variable"),
  radioButtons(
    inputId = "viz_3inputid",
    label = "Select plot type:",
    choices = c("Heart Rate", "Blood Pressure", "Daily Steps", "Physical Activity Level"),
    selected = "Heart Rate"
  )
)


viz_3_main_panel <- mainPanel(
  h2("3. Potential Correlation between Salary and Physical Health"),
  h3("Salary vs. Physical Health"),
  plotlyOutput(outputId = "sal_phy_plot"),
)

viz_3_tab <- tabPanel("Potential Correlation between Salary and Physical Health",
  sidebarLayout(
    viz_3_sidebar,
    viz_3_main_panel,
  )
)





## CONCLUSIONS TAB INFO

conclusion_tab <- tabPanel("Conclusion",
 h1("Conclusion"),

 img(src = 'https://res.cloudinary.com/tripactions/image/upload/f_auto/q_auto/v1661189557/compose/blog/refresh-erg-employee-wellness.jpg?fit=pad&w=760', height="30%", width="30%", align="left"),
 
 
 h3("Takeaway 1"),
 p("To illustrate the varying levels of physical activity required by different 
    occupations, our first graph highlights the significance of acknowledging these 
    differences. By considering the physical activity levels in various occupations, 
    employers can adjust their lifestyle to mitigate potential risks associated with 
    excessive physical strain. In addition, individuals, such as college students who 
    are considering these occupations, can make more informed decisions about their 
    career paths."),
 h3("Takeaway 2"),
 p("Sleep quality is important for both physical and mental functioning. Although 
   sleep quality severely influenced by individual lifestyle, we can generalize the 
   average sleep quality of occupations based on responses from individuals currently 
   in those positions. Adequate sleep is critical for maintaining cognitive functions 
   such as memory, attention, and decision-making abilities. While lack of sleep over 
   time can contribute to various health issues such as obesity, type 2 diabetes, high 
   blood pressure, heart disease, stroke, poor mental health, and even early death 
   (Centers for Disease Control, 2022). Examining the correlation between job type 
   and sleep health is crucial for long-term career success and well-being."),
 h3("Takeaway 3"),
 p("Have you ever wondered if the physical demands are adequately compensated? 
   Though it may seem straightforward, fair compensation for the physical burden of 
   a job serves as a significant motivator for workers. Aligning wages with job 
   demands contributes to the economic equity by recognizing the value of different 
   types of work. Furthermore, ensuring wages reflect the physical burden of the 
   jobs can lead to increased efficiency and performance in the workplace."),
 h3("Broader Implications"),
 
 img(src = 'https://cdn.papershift.com/20220808102940/employee-wellness-program-at-workplaces-explained-by-Papershift-min-910x500.jpeg', height="30%", width="30%", align="right"),
 
 p("The data on physical health and wages disparities across occupations carries 
   significant Implications for various aspects of our society. By understanding 
   the physical demand and compensation associated with different jobs, employers 
   and policymakers can enhance workforce well-being and job satisfaction while 
   also promoting public health."),
   
 p("It should be noted that personal well-being can have broader economic 
   implications internationally. Employee struggles such as insufficient sleep has 
   been linked to lost GDP and lower labor productivity in industrialized countries 
   such as Canada, Germany, Japan, the United Kingdom, and the United States 
   (Hafner et al, 2017). In the United States alone, sleep deprivation leads to an 
   estimated $411 billion loss annually from the nation’s GDP (Preidt 2016). Thus, 
   addressing the physical demands of occupation and its compensation does not only 
   contribute to greater economic equity and social justice, but also link to 
   national issues."),
   
 p("Our findings, presented through comprehensive graphs and charts focusing on 
   various job sectors and income, allow us to observe health trends across 
   different jobs and relative salaries. This data can inform career guidance 
   and education to students, empowering individuals to make informed decisions 
   about their career paths. Overall, utilizing the quantified pattern of how the 
   nature and remuneration of work influence physical health has potential to drive 
   positive change across multiple domains, facilitating healthier work environments, 
   lifestyles, and a more prosperous society.")

)


ui <- navbarPage("The Relationship Between Occupation and Physical Health",
  theme = my_theme,
  overview_tab,
  viz_1_tab,
  viz_2_tab,
  viz_3_tab,
  conclusion_tab
)
