# INFO 201 Final Project -- Final Deliverable
# Section BH
# Group member: Sera Lee, Lele Zhang, Ivette Ivanov, Sohyun Han

library(ggplot2)
library(plotly)
library(dplyr)
library(bslib)
library(shiny)

# Color theme
my_theme <- bs_theme(bg = "white", #background
                     fg = "black", #foreground color
                     primary = "#FFC0CB", # primary color
)



## OVERVIEW TAB INFO

overview_tab <- tabPanel("Introduction",
   tags$b("BH-5 Group Members:"), p("Sohyun Han, Sera Lee, Ivette Immanov, Lele Zhang"),
   h1("The Impact of Occupation on Physical Health"),
   h3("Introduction"),
   
   img(src = 'https://cdn.pixabay.com/photo/2017/03/04/13/12/alarm-clock-2116007_1280.jpg', height="40%", width="40%", align="right"),
   
   p("In today’s society, where work plays a central role in our daily lives, 
   understanding the impact of specific occupation on individuals’ physical health 
   is a crucial topic. The background of one’s job can severely influence well-being, 
   including the risk factors to necessary lifestyle adjustments."),
   
   p("Past studies on work and health have focused on physical safety and mitigating occupational hazards. 
   Although these concerns still remain, this investigation aims to expand the discussion 
   to include deeper factors such as, mental health, stress, and sleep health."),
   
   p("By examining and comparing the data collected, we not only enhance our understanding 
   of individual health outcomes but also inform a broader societal discussion on work-life 
   balance, workplace wellness, and public health policies. Our discussion will dive into 
   the compelling questions aimed to investigate the correlation between one’s occupation 
   and physical health and to recognize the quantified pattern that emerges from this exploration."),
   
   
   tags$ol(
   tags$li(tags$b("How do physical activity levels vary among different occupations?")),
   p(""),
   tags$li(tags$b("What occupations among the dataset have the best/worst (average) quality of sleep?")),
   p(""),
   tags$li(tags$b("Does a higher salary in high-stress jobs equate to poorer physical health?")),
   p(""),),
   
   h3("Datasets Used"),
   p("The data set has been compiled from two sources: the U.S. Bureau of Labor Statistics Occupational Employment 
      and Wage Statistics (OEWS) program and Laksika Tharmalingam’s Sleep and Health dataset on Kaggle.
      The OEWS program surveys employers in all industries across all states including the District of Columbia. 
      The data is estimated based on responses collected over a 3-year period: May 2022, November 2021, May 2021, 
      November 2020, May 2020, and November 2019."),
   
   p(""),
   
   tags$ul(
   tags$b(tags$li(em("May 2022 National Occupational Employment and Wage Estimates."))),
   a("https://www.bls.gov/oes/current/oes_nat.htm"),
   p(""),
   p("The Sleep and Health dataset was collected and generated by Laksika Tharmalingam in 2023, 
      it was last modified on April 25, 2023, and no other external source is specified."),

   tags$li(tags$b(em("Sleep Health and Lifestyle Dataset."))),
   p(""),
   
   a("https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset"),
   p("The Sleep and Health dataset was collected and generated by Laksika Tharmalingam in 2023, 
      it was last modified on April 25, 2023, and no other external source is specified."),

   tags$li(tags$b("The comprehensive data set is available here on Github:")),
   a("https://github.com/imivanov-2034391/Info_201_Final_Project/blob/main/Comprehensive%20Physical%20Health%20and%20Occupational%20Statistics%20Dataset.csv"),
   
   ),
   p(""),
   h3("Limitations & Challenges"),
   p("The following visualizations are very much a limited snapshot of the sleep health of individuals 
      in a particular set of occupations within the past 3 years in the United States (as written in 2024)."),
   
   img(src = 'https://haverfordlibrary.org/wp-content/uploads/2016/09/Bureau_of_labor_statistics_logo-1024x897.png', height="25%", width="25%", align="right"),
      
   tags$b("Many types of occupations are not included, and thus this cannot be taken as truly representative 
      of the diverse workforce of the U.S. There is a small number of data points even within the existing 
      occupations in the dataset, and is a rather small sample of the variety of working individuals and their 
      sleeping patterns given the size of the U.S. population."),
   
   p(""),
    
   p("Additionally, the Sleep Health and Lifestyle dataset was acquired from Kaggle for student 
      research purposes and may therefore be biased."),
      
   p("As for the salary and wage statistics from the National Occupational 
      Employment and Wage Estimates dataset, there are two main challenges to be noted here. 
      Primarily, the timeframe in which the data was collected took place 
      over the COVID-19 pandemic and may have negatively influenced the wage statistics."),
      
      
  p("There is also the additional matter of how these statistics are not representative of change over a long period of time. 
      It is possible that the relationship between sleep health and occupation could have more variation and complexities to 
      consider over an entire decade for example, as opposed to a few years, especially as this is only a glimpse into the 
      momentary health of a few individuals."),
    
  tags$b("Overall, our compiled dataset is rather limited in terms of timeframe, the types of occupations represented, and simply the number of data points available."),
   
   h3("Implications"),
   p("context"),
   h3("Related Work"),
   
   p(""),
 tags$ul(
   
  tags$li(tags$b(em("CDC (2022) Sleep for good health, Centers for Disease Control and Prevention."))),
      a("https://www.cdc.gov/sleep/features/getting-enough-sleep.html"),
      p(""),
  
      p("Contains background information on sleep health and quality, along with other sources on sleep quality, 
      disorders, and outreach programs. We used the CDC website in order to gain a basic understanding of how sleep may impact health."),
      
  tags$li(tags$b(em("Functional and economic impact of sleep loss and sleep-related disorders’, 
                        in Sleep Disorders and Sleep Deprivation: An Unmet Public Health Problem. National Academies Press (US)."))),
      a("https://www.ncbi.nlm.nih.gov/books/NBK19958/"),
      p(""),
      
      p("A source that looks largely at the broader economic impact of sleep deprivation on the healthcare system. 
        While that isn’t the main focus of our project, it is one of the references that made us consider how economics 
        and finances play a role in regard to sleep deprivation."),
      
  tags$li(tags$b(em("Who gets the best sleep? Ethnic and socioeconomic 
                        factors related to sleep complaints, Journal of Sleep Medicine, 11(5), pp. 470–478. "))),
      a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2861987/ "),
      p("Indicates that there are a variety of socioeconomic factors that may lead to insufficient sleep, including wages."),
      
      p("A source that looks largely at the broader economic impact of sleep deprivation on the healthcare system. 
        While that isn’t the main focus of our project, it is one of the references that made us consider how economics 
        and finances play a role in regard to sleep deprivation."),
  
  tags$li(tags$b(em("The association between sleep disorders, employment, and income among adults in the United States"))),
      a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9340609/"),
      p("It shows that people with poor sleep health have lower unemployment rates, 
      lower wages, and higher utilization of welfare income. 
      Considers a number of demographic factors such as age, race, and medical conditions."),
      
      p("A source that looks largely at the broader economic impact of sleep deprivation on the healthcare system. 
        While that isn’t the main focus of our project, it is one of the references that made us consider how economics 
        and finances play a role in regard to sleep deprivation."),
  
  
  tags$li(tags$b(em("‘Why sleep matters—the economic costs of insufficient sleep’, Rand Health Quarterly, 6(4), p. 11."))),
      a("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5627640/"),
      p(""),
      
      p("Frames the issue of insufficient sleep as a matter of public health, and details everything related to that, 
        including economic factors, has the main objective of quantifying the cost of insufficient sleep. "),
 ),) 



## VIZ 1 TAB INFO

viz_1_sidebar <- sidebarPanel(
  h3("Options"),
  checkboxInput (
    inputId = "phy_occ_plot_60" ,
    label = "Physical activity levels above 60"
  )
  
)

viz_1_main_panel <- mainPanel(
  h2("1.Physical activity levels among different occupations"),
  h3("Physical Activity vs. Occupation"),
  plotlyOutput(outputId = "phy_occ_plot")
)

viz_1_tab <- tabPanel("Physical Activity among Occupations",
  sidebarLayout(
    viz_1_sidebar,
    viz_1_main_panel
  )
)



## VIZ 2 TAB INFO

viz_2_sidebar <- sidebarPanel(
  h3("Options"),
  radioButtons(
    inputId = "sle_occ_plot_type",
    label = "Select plot type:",
    choices = c("Best Quality of Sleep", "Worst Quality of Sleep"),
    selected = "Best Quality of Sleep"
  )
)

viz_2_main_panel <- mainPanel(
  h2("2. Best/worst (average) quality of sleep among different occupations"),
  h3("Sleep Median vs. Occupation"),
  plotlyOutput(outputId = "sle_occ_plot")
)

viz_2_tab <- tabPanel("Sleep Quality among Occupation",
                      sidebarLayout(
                        viz_2_sidebar,
                        viz_2_main_panel
                      )
)


## VIZ 3 TAB INFO

viz_3_sidebar <- sidebarPanel(
  h3("Options"),
  #TODO: Put inputs for modifying graph here
)

viz_3_main_panel <- mainPanel(
  h2("3. Potential correlation between salary and physical health"),
  h3("Salary vs. Physical Health"),
  plotlyOutput(outputId = "sal_phy_plot")
)

viz_3_tab <- tabPanel("Potential Correlation between Salary and Physical Health",
  sidebarLayout(
    viz_3_sidebar,
    viz_3_main_panel
  )
)



## CONCLUSIONS TAB INFO

conclusion_tab <- tabPanel("Conclusion",
 h1("Conclusion"),
 h3("Takeaway 1"),
 p("context"),
 h3("Takeaway 2"),
 p("context"),
 h3("Takeaway 3"),
 p("context"),
 h3("Important Insights"),
 p("context"),
 h3("Broader Implications"),
 p("context")

)


ui <- navbarPage("The Impact of Occupation on Physical Health Report",
  overview_tab,
  viz_1_tab,
  viz_2_tab,
  viz_3_tab,
  conclusion_tab
)
