# INFO 201 Final Project -- Final Deliverable
# Section BH
# Group member: Sera Lee, Lele Zhang, Ivette Ivanov, Sohyun Han

library(ggplot2)
library(plotly)
library(dplyr)
library(bslib)
library(shiny)

# Color theme
my_theme <- bs_theme(bg = "white", #background
                     fg = "black", #foreground color
                     primary = "#FFC0CB", # primary color
)



## OVERVIEW TAB INFO

overview_tab <- tabPanel("Introduction",
   h1("The Impact of Occupation on Sleep Health"),
   h4("INFO 201 BH-5 Final Project"),
   tags$b("Group Members:"), p("Sohyun Han, Sera Lee, Ivette Immanov, Lele Zhang"),
   p("March 6th, 2024"),
   h3("Introduction"),
   
   img(src = 'https://cdn.pixabay.com/photo/2017/03/04/13/12/alarm-clock-2116007_1280.jpg', height="40%", width="40%", align="right"),
   
   p("In today’s society, where work plays a central role in our daily lives, 
   understanding the impact of specific occupation on individuals’ physical health 
   is a crucial topic. The background of one’s job can severely influence well-being, 
   including the risk factors to necessary lifestyle adjustments."),
   
   p("Past studies on work and health have focused on physical safety and mitigating occupational hazards. 
   Although these concerns still remain, this investigation aims to expand the discussion 
   to include deeper factors such as, mental health, stress, and sleep health."),
   
   p("By examining and comparing the data collected, we not only enhance our understanding 
   of individual health outcomes but also inform a broader societal discussion on work-life 
   balance, workplace wellness, and public health policies. Our discussion will dive into 
   the compelling questions aimed to investigate the correlation between one’s occupation 
   and physical health and to recognize the quantified pattern that emerges from this exploration."),
   
   tags$b("      1. How do physical activity levels vary among different occupations?"),
   p(""),
   tags$b("      2. What occupations among the dataset have the best/worst (average) quality of sleep?"),
   p(""),
   tags$b("      3. Does a higher salary in high-stress jobs equate to poorer physical health?"),
   p(""),
   
   h3("Datasets Used"),
   p("The data set has been compiled from two sources: the U.S. Bureau of Labor Statistics Occupational Employment 
      and Wage Statistics (OEWS) program and Laksika Tharmalingam’s Sleep and Health dataset on Kaggle.
      The OEWS program surveys employers in all industries across all states including the District of Columbia. 
      The data is estimated based on responses collected over a 3-year period: May 2022, November 2021, May 2021, 
      November 2020, May 2020, and November 2019."),
   
   p(""),
   em("May 2022 National Occupational Employment and Wage Estimates."),
   a("https://www.bls.gov/oes/current/oes_nat.htm"),
   p(""),
   p("The Sleep and Health dataset was collected and generated by Laksika Tharmalingam in 2023, 
      it was last modified on April 25, 2023, and no other external source is specified."),

   em("Sleep Health and Lifestyle Dataset."),
   p(""),
   
   p("Laksika Tharmalingam."),
   a("https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset"),
   p("The Sleep and Health dataset was collected and generated by Laksika Tharmalingam in 2023, 
      it was last modified on April 25, 2023, and no other external source is specified."),

   p("The comprehensive data set is available here on Github:"),
   a("https://github.com/imivanov-2034391/Info_201_Final_Project/blob/main/Comprehensive%20Physical%20Health%20and%20Occupational%20Statistics%20Dataset.csv"),
   
   p(""),
   h3("Related Work"),
   p("context"),
   h3("Implications"),
   p("context"),
   h3("Limitations & Challenges"),
   p(""),
   
   
)



## VIZ 1 TAB INFO

viz_1_sidebar <- sidebarPanel(
  h3("Options"),
  checkboxInput (
    inputId = "phy_occ_plot_60" ,
    label = "Physical activity levels above 60"
  )
  
)

viz_1_main_panel <- mainPanel(
  h2("1.How do physical activity levels vary among different occupations?"),
  h3("Physical Activity vs. Occupation"),
  plotlyOutput(outputId = "phy_occ_plot")
)

viz_1_tab <- tabPanel("Physical Activity vs. Occupation",
  sidebarLayout(
    viz_1_sidebar,
    viz_1_main_panel
  )
)



## VIZ 2 TAB INFO

viz_2_sidebar <- sidebarPanel(
  h3("Options"),
  radioButtons(
    inputId = "sle_occ_plot_type",
    label = "Select plot type:",
    choices = c("Best Quality of Sleep", "Worst Quality of Sleep"),
    selected = "Best Quality of Sleep"
  )
)

viz_2_main_panel <- mainPanel(
  h2("2. What occupations among the dataset have the best/worst (average) quality of sleep?"),
  h3("Sleep Median vs. Occupation"),
  plotlyOutput(outputId = "sle_occ_plot")
)

viz_2_tab <- tabPanel("Median Sleep vs. Occupation",
                      sidebarLayout(
                        viz_2_sidebar,
                        viz_2_main_panel
                      )
)


## VIZ 3 TAB INFO

viz_3_sidebar <- sidebarPanel(
  h3("Options"),
  #TODO: Put inputs for modifying graph here
)

viz_3_main_panel <- mainPanel(
  h2("3. Does a higher salary in high-stress jobs equate to poorer physical health?"),
  h3("Salary vs. Physical Health"),
  plotlyOutput(outputId = "sal_phy_plot")
)

viz_3_tab <- tabPanel("Salary vs. Physical Health",
  sidebarLayout(
    viz_3_sidebar,
    viz_3_main_panel
  )
)



## CONCLUSIONS TAB INFO

conclusion_tab <- tabPanel("Conclusion",
 h1("Conclusion"),
 h3("Takeaway 1"),
 p("context"),
 h3("Takeaway 2"),
 p("context"),
 h3("Takeaway 3"),
 p("context"),
 h3("Important Insights"),
 p("context"),
 h3("Broader Implications"),
 p("context")

)


ui <- navbarPage("INFO 201 Final Project - BH Group 5",
  overview_tab,
  viz_1_tab,
  viz_2_tab,
  viz_3_tab,
  conclusion_tab
)
